apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curator
              image: unifiedstreaming/curator:5.5.1
              args: ["--config", "/etc/curator/config.yaml", "/etc/curator/delete-indices"]
              volumeMounts:
                - name: curator
                  mountPath: /etc/curator
          volumes:
            - name: curator
              configMap:
                name: curator
          restartPolicy: OnFailure

